In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
dataset = pd.read_csv('/content/drive/MyDrive/machine-learning-a-Z/decision_tree_regression/Position_Salaries.csv')

In [6]:
dataset.head()

            Position  Level  Salary
0   Business Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000
4    Country Manager      5  110000

In [7]:
X = dataset.iloc[:,1:-1].values
Y= dataset.iloc[:,-1].values

In [8]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [9]:
Y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

In [10]:
from sklearn.tree import DecisionTreeRegressor

In [11]:
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X,Y)

DecisionTreeRegressor(random_state=0)

In [13]:
regressor.predict([[6.5]])

array([150000.])